server:
  listen: 10.10.10.23@53

remote:
  - id: local_primary
    address: 10.10.10.21@53

acl:
  - id: allow_notify
    address: 10.10.10.21  
    action: notify

zone:
  - domain: domain.local
    master: local_primary
    acl: allow_notify
