server:
  listen: 0.0.0.0@53

remote:
  - id: master
    address: 10.10.30.11@53

acl:
  - id: allow_notify
    address: 10.10.30.11
    action: notify

zone:
  - domain: domain.local
    master: master
    acl: allow_notify
