server:
  listen: 10.10.10.11@53

mod-dnstap:
  - id: tap
    sink: "unix:/tmp/dnstap.sock"
    log-queries: on
    log-responses: on

remote:
  - id: site_a_slave1
    address: 10.10.10.12@53
  - id: site_a_slave2
    address: 10.10.10.13@53
  - id: site_b_primary
    address: 10.10.10.21@53

acl:
  - id: allow_transfer
    address: [10.10.10.12, 10.10.10.13, 10.10.10.21]
    action: transfer
  - id: allow_notify_from_b
    address: 10.10.10.21
    action: notify

template:
  - id: default
    global-module: mod-dnstap/tap
    storage: /var/lib/knot
    file: "%s.zone"

zone:
  - domain: domain.local
    notify: [site_a_slave1, site_a_slave2, site_b_primary]
    acl: [allow_transfer, allow_notify_from_b]
